/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessLinkageProgramRouteImport } from './routes/business-linkage-program'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as BusinessLinkageProgramParcoursEntrepreneurRouteImport } from './routes/business-linkage-program_.parcours-entrepreneur'
import { Route as BusinessLinkageProgramFinanceVerteDurableRouteImport } from './routes/business-linkage-program_.finance-verte-durable'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBuilderSlugRouteImport } from './routes/admin.builder.$slug'

const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLinkageProgramRoute = BusinessLinkageProgramRouteImport.update({
  id: '/business-linkage-program',
  path: '/business-linkage-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLinkageProgramParcoursEntrepreneurRoute =
  BusinessLinkageProgramParcoursEntrepreneurRouteImport.update({
    id: '/business-linkage-program_/parcours-entrepreneur',
    path: '/business-linkage-program/parcours-entrepreneur',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessLinkageProgramFinanceVerteDurableRoute =
  BusinessLinkageProgramFinanceVerteDurableRouteImport.update({
    id: '/business-linkage-program_/finance-verte-durable',
    path: '/business-linkage-program/finance-verte-durable',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuilderSlugRoute = AdminBuilderSlugRouteImport.update({
  id: '/admin/builder/$slug',
  path: '/admin/builder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
  '/admin/login': typeof AdminLoginRoute
  '/business-linkage-program/finance-verte-durable': typeof BusinessLinkageProgramFinanceVerteDurableRoute
  '/business-linkage-program/parcours-entrepreneur': typeof BusinessLinkageProgramParcoursEntrepreneurRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
  '/admin/login': typeof AdminLoginRoute
  '/business-linkage-program/finance-verte-durable': typeof BusinessLinkageProgramFinanceVerteDurableRoute
  '/business-linkage-program/parcours-entrepreneur': typeof BusinessLinkageProgramParcoursEntrepreneurRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
  '/admin/login': typeof AdminLoginRoute
  '/business-linkage-program_/finance-verte-durable': typeof BusinessLinkageProgramFinanceVerteDurableRoute
  '/business-linkage-program_/parcours-entrepreneur': typeof BusinessLinkageProgramParcoursEntrepreneurRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/builder/$slug': typeof AdminBuilderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
    | '/admin/login'
    | '/business-linkage-program/finance-verte-durable'
    | '/business-linkage-program/parcours-entrepreneur'
    | '/pages/$slug'
    | '/admin/builder/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
    | '/admin/login'
    | '/business-linkage-program/finance-verte-durable'
    | '/business-linkage-program/parcours-entrepreneur'
    | '/pages/$slug'
    | '/admin/builder/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
    | '/admin/login'
    | '/business-linkage-program_/finance-verte-durable'
    | '/business-linkage-program_/parcours-entrepreneur'
    | '/pages/$slug'
    | '/admin/builder/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessLinkageProgramRoute: typeof BusinessLinkageProgramRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExpertisesRoute: typeof ExpertisesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BusinessLinkageProgramFinanceVerteDurableRoute: typeof BusinessLinkageProgramFinanceVerteDurableRoute
  BusinessLinkageProgramParcoursEntrepreneurRoute: typeof BusinessLinkageProgramParcoursEntrepreneurRoute
  PagesSlugRoute: typeof PagesSlugRoute
  AdminBuilderSlugRoute: typeof AdminBuilderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-linkage-program': {
      id: '/business-linkage-program'
      path: '/business-linkage-program'
      fullPath: '/business-linkage-program'
      preLoaderRoute: typeof BusinessLinkageProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-linkage-program_/parcours-entrepreneur': {
      id: '/business-linkage-program_/parcours-entrepreneur'
      path: '/business-linkage-program/parcours-entrepreneur'
      fullPath: '/business-linkage-program/parcours-entrepreneur'
      preLoaderRoute: typeof BusinessLinkageProgramParcoursEntrepreneurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-linkage-program_/finance-verte-durable': {
      id: '/business-linkage-program_/finance-verte-durable'
      path: '/business-linkage-program/finance-verte-durable'
      fullPath: '/business-linkage-program/finance-verte-durable'
      preLoaderRoute: typeof BusinessLinkageProgramFinanceVerteDurableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/builder/$slug': {
      id: '/admin/builder/$slug'
      path: '/admin/builder/$slug'
      fullPath: '/admin/builder/$slug'
      preLoaderRoute: typeof AdminBuilderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessLinkageProgramRoute: BusinessLinkageProgramRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExpertisesRoute: ExpertisesRoute,
  AdminLoginRoute: AdminLoginRoute,
  BusinessLinkageProgramFinanceVerteDurableRoute:
    BusinessLinkageProgramFinanceVerteDurableRoute,
  BusinessLinkageProgramParcoursEntrepreneurRoute:
    BusinessLinkageProgramParcoursEntrepreneurRoute,
  PagesSlugRoute: PagesSlugRoute,
  AdminBuilderSlugRoute: AdminBuilderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
