/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessLinkageProgramRouteImport } from './routes/business-linkage-program'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLinkageProgramRoute = BusinessLinkageProgramRouteImport.update({
  id: '/business-linkage-program',
  path: '/business-linkage-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-linkage-program': typeof BusinessLinkageProgramRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/expertises': typeof ExpertisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-linkage-program'
    | '/contact'
    | '/events'
    | '/expertises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessLinkageProgramRoute: typeof BusinessLinkageProgramRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  ExpertisesRoute: typeof ExpertisesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-linkage-program': {
      id: '/business-linkage-program'
      path: '/business-linkage-program'
      fullPath: '/business-linkage-program'
      preLoaderRoute: typeof BusinessLinkageProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessLinkageProgramRoute: BusinessLinkageProgramRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  ExpertisesRoute: ExpertisesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
